version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0.5-management
    container_name: queues-manager
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - app-network

  m1:
    container_name: m1-microservice
    build: m1/.
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - m1/.env
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    