name: CI for m2 microservice

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build_and_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Checkout and setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'm2/package-lock.json'

      - name: Install dependencies
        working-directory: m2
        run: npm install

      - name: Lint code
        working-directory: m2
        run: npm run pr:lint